#!/usr/bin/env python3
import os
import re
import json
import yaml

# --- CONFIGURATION ---
# Path to search for markdown files (relative to this script)
VAULT_DIR = "."  
# Path to output the compiled JavaScript data file
OUTPUT_JS_PATH = "./_app/data.js"

# Folders to completely skip during compiling
EXCLUDE_DIRS = {".obsidian", ".trash", "templates", "_app", "assets", "_templates"}

def parse_markdown_sections(content):
    """
    Extracts the custom ## sections (vista, text, epoché, wissen, etc.) 
    and splits them into bilingual (Chinese/English) column contents.
    """
    sections = {}
    # Matches markdown headers like "## 觀景 / vista" or "##  拆建/ deconstruct"
    header_pattern = re.compile(
        r'^##\s*(?:[^/]+)\/\s*([a-zA-Z\s]+?)\s*$', 
        re.MULTILINE
    )
    
    # Find all header positions
    headers = list(header_pattern.finditer(content))
    
    for i, match in enumerate(headers):
        section_name = match.group(1).strip().lower()
        # Clean section names to match standard database fields
        if "epoch" in section_name:
            section_name = "epoche"
        elif "critic" in section_name:
            section_name = "critics"
            
        # Determine the start and end of this section's body text
        start_idx = match.end()
        end_idx = headers[i+1].start() if i + 1 < len(headers) else len(content)
        section_body = content[start_idx:end_idx].strip()
        
        # Strip trailing horizontal rule dividers (---) often used between sections
        section_body = re.sub(r'\s*---\s*$', '', section_body).strip()
        
        # Extract bilingual columns inside <div style="display: flex;"> structure
        # Col 1: Chinese (left), Col 2: English (right)
        div_pattern = re.compile(
            r'<div\s+style="display:\s*flex;.*?<div\s+style="flex:\s*1;".*?markdown="1">(.*?)</div>.*?<div\s+style="flex:\s*1;.*?color:.*?markdown="1">(.*?)</div>.*?</div>',
            re.DOTALL | re.IGNORECASE
        )
        
        div_match = div_pattern.search(section_body)
        if div_match:
            zh_text = div_match.group(1).strip()
            en_text = div_match.group(2).strip()
            sections[section_name] = {
                "zh": zh_text,
                "en": en_text
            }
        else:
            # Fallback if no flex container is used
            sections[section_name] = {
                "zh": section_body,
                "en": ""
            }
            
    return sections

def compile_archive():
    registry = []
    
    print("Scanning Obsidian vault files...")
    for root, dirs, files in os.walk(VAULT_DIR):
        # Skip excluded directories
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        
        for file in files:
            if not file.endswith(".md"):
                continue
                
            file_path = os.path.join(root, file)
            
            with open(file_path, "r", encoding="utf-8") as f:
                raw_content = f.read()
                
            # Parse YAML frontmatter
            if raw_content.startswith("---"):
                parts = raw_content.split("---", 2)
                if len(parts) >= 3:
                    yaml_block = parts[1]
                    body_block = parts[2]
                    
                    try:
                        metadata = yaml.safe_load(yaml_block)
                    except Exception as e:
                        print(f"Error parsing YAML in {file_path}: {e}")
                        continue
                        
                    if not metadata or "id" not in metadata:
                        continue # Skip markdown files without standard IDs
                        
                    # Extract bilingual sections from the body text
                    metadata["content"] = parse_markdown_sections(body_block)
                    registry.append(metadata)

    # Sort the registry alphabetically by ID so the output is deterministic
    registry.sort(key=lambda x: x.get("id", ""))
    
    # Write to target data.js file wrapping the registry in a global export
    os.makedirs(os.path.dirname(OUTPUT_JS_PATH), exist_ok=True)
    with open(OUTPUT_JS_PATH, "w", encoding="utf-8") as out:
        out.write("// Automatically generated by compile_archive.py. Do not edit manually.\n\n")
        out.write("const RAW_REGISTRY = ")
        # Pretty print JSON format compatible with JavaScript arrays
        out.write(json.dumps(registry, ensure_ascii=False, indent=2))
        out.write(";\n")
        
    print(f"Success! Compiled {len(registry)} metadata nodes into {OUTPUT_JS_PATH}")

if __name__ == "__main__":
    # Ensure PyYAML is installed
    try:
        import yaml
    except ImportError:
        print("Required package 'PyYAML' not found. Installing...")
        os.system("pip install pyyaml")
        import yaml
        
    compile_archive()